{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "v2ray.serviceAccountName" . }}
  labels:
{{ include "v2ray.labels" . | indent 4 }}
{{- end -}}
